// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:rnd_proj/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVOmOHzMI-pzzDyZC8Q1xc0QTRkRAOIPU',
    appId: '1:945388284295:web:b69bd333c79f521ee18b22',
    messagingSenderId: '945388284295',
    projectId: 'rnd-database-21030',
    authDomain: 'rnd-database-21030.firebaseapp.com',
    storageBucket: 'rnd-database-21030.firebasestorage.app',
    measurementId: 'G-752H20S4DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcn0gZGBQFGT5VJybW1JF-M6w2frR0l44',
    appId: '1:945388284295:android:dc70c4036755c5f6e18b22',
    messagingSenderId: '945388284295',
    projectId: 'rnd-database-21030',
    storageBucket: 'rnd-database-21030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSfw4sCAGIXPbIiIXBRLUs1n9-leExewk',
    appId: '1:945388284295:ios:9fc673a771bc14e5e18b22',
    messagingSenderId: '945388284295',
    projectId: 'rnd-database-21030',
    storageBucket: 'rnd-database-21030.firebasestorage.app',
    iosBundleId: 'com.example.rndProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSfw4sCAGIXPbIiIXBRLUs1n9-leExewk',
    appId: '1:945388284295:ios:9fc673a771bc14e5e18b22',
    messagingSenderId: '945388284295',
    projectId: 'rnd-database-21030',
    storageBucket: 'rnd-database-21030.firebasestorage.app',
    iosBundleId: 'com.example.rndProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVOmOHzMI-pzzDyZC8Q1xc0QTRkRAOIPU',
    appId: '1:945388284295:web:e6af1971fbc435f5e18b22',
    messagingSenderId: '945388284295',
    projectId: 'rnd-database-21030',
    authDomain: 'rnd-database-21030.firebaseapp.com',
    storageBucket: 'rnd-database-21030.firebasestorage.app',
    measurementId: 'G-C5X03DJ63L',
  );

}